version: '3.4'

services:
  beerdispenser.webui:
    image: ${DOCKER_REGISTRY-}beerdispenser
    container_name: beerdispenser.webui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
