services:
   sqlserver:
      image: mcr.microsoft.com/mssql/server
      container_name: sqlserver
      restart: always
      ports:
        - "1433:1433"
      environment:
        - MSSQL_SA_PASSWORD=Pa$$w0rd!
        - ACCEPT_EULA=Y
